"""forgeinkey project with users10

Revision ID: 462856ff2b53
Revises: 2ad5e835d3f7
Create Date: 2024-05-11 21:10:24.733759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462856ff2b53'
down_revision: Union[str, None] = '2ad5e835d3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
