"""forgeinkey project with users6

Revision ID: 5d48949ae7c0
Revises: b4ef3a679441
Create Date: 2024-05-11 19:18:00.659103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d48949ae7c0'
down_revision: Union[str, None] = 'b4ef3a679441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
