"""add field in model user image

Revision ID: 7eb510894493
Revises: 6a1a9ba95be2
Create Date: 2024-05-10 20:42:42.924524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb510894493'
down_revision: Union[str, None] = '6a1a9ba95be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_image')
    # ### end Alembic commands ###
