"""add model finance profit1

Revision ID: ae021311ee99
Revises: 75d54158666e
Create Date: 2024-05-13 20:29:32.845603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae021311ee99'
down_revision: Union[str, None] = '75d54158666e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance', 'all_profits')
    op.drop_column('finance', 'all_losses')
    op.create_unique_constraint(None, 'projects', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.add_column('finance', sa.Column('all_losses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finance', sa.Column('all_profits', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
