"""forgeinkey project with users2

Revision ID: c6e829af35a2
Revises: eb63440ea83f
Create Date: 2024-05-11 18:20:08.819909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e829af35a2'
down_revision: Union[str, None] = 'eb63440ea83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'project_id')
    # ### end Alembic commands ###
