"""forgeinkey project with users7

Revision ID: d8fe4ca9401f
Revises: 5d48949ae7c0
Create Date: 2024-05-11 19:20:45.978086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fe4ca9401f'
down_revision: Union[str, None] = '5d48949ae7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
