"""forgeinkey project with users12

Revision ID: e51a05a1982e
Revises: c783b9bb947e
Create Date: 2024-05-11 22:17:24.633641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51a05a1982e'
down_revision: Union[str, None] = 'c783b9bb947e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_prod_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_column('tasks', 'prod_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('prod_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_prod_id_fkey', 'tasks', 'projects', ['prod_id'], ['id'])
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###
